_target_: pytorch_lightning.Trainer

accelerator: ${accelerator}
devices: 1

min_epochs: 0
max_epochs: 1
log_every_n_steps : 100
val_check_interval : 0.5

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 2

precision: 32

# fastdev
fast_dev_run: False

# For profiling
#profiler : 'pytorch'
#val_check_interval : 5
#max_steps: 8
