_target_: pytorch_lightning.Trainer

accelerator: ${accelerator}
devices: 1
detect_anomaly: True
# gradient_clip_val: 0.5


min_epochs: 0
max_epochs: 200
log_every_n_steps : 100
val_check_interval : 0.25

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0

precision: 32

# fastdev
fast_dev_run: False

# For profiling
#profiler : 'pytorch'
#val_check_interval : 5
#max_steps: 8
