_target_: prosailvae.models.lightning_module.ProsailVAELightningModule
model:
  _target_: prosailvae.simvae.SimVAE
  config:
    _target_: prosailvae.simvae.SimVAEConfig
    encoder:
      _target_: prosailvae.encoders.ProsailRNNEncoder
      config:
        _target_: prosailvae.encoders.EncoderConfig
        encoder_type: "rnn"
        input_size: 17
        io_coeffs:
          _target_: prosailvae.utils.utils.IOStandardizeCoeffsFromDisk
          data_dir: "/usr/local/stok/DATA/MMDC/ProsailVAE/PROSAILVAE/s2_patch_dataset/"
        output_size: 11
    decoder:
      _target_: prosailvae.decoders.ProsailSimulatorDecoder
      prosailsimulator:
        _target_: prosailvae.ProsailSimus.ProsailSimulator
        device: "cpu"
        R_down: 1
        prospect_version: "5"
      ssimulator:
        _target_: prosailvae.ProsailSimus.SensorSimulator
        rsr_file: "/home/inglada/Dev/MMDC/prosailvae/data/sentinel2.rsr"
        device: "cpu"
        apply_norm: True
        bands: [1, 2, 3, 4, 5, 6, 7, 8, 11, 12]
        R_down: 1
      loss_type: "diag_nll"
    lat_space:
      _target_: prosailvae.latentspace.TruncatedNormalLatent
      device: "cpu"
      latent_dim: 11
      kl_type: "tnu"
      disabled_latent: []
      disabled_latent_values: []
    sim_space:
      _target_: prosailvae.simspaces.LinearVarSpace
      latent_dim: 11
      device: "cpu"
      var_bounds_type: "legacy"
    deterministic: False
    reconstruction_loss:
      _target_: prosailvae.loss.NLLLoss
      loss_type: "diag_nll"
    supervised: False
    device: "cpu"
    beta_kl: 0.0
    beta_index: 0.0
    beta_cyclical: 0.0
    snap_cyclical: False
    logger_name: ""
    inference_mode: False
