tensorboard:
  _target_ : pytorch_lightning.loggers.TensorBoardLogger
  save_dir : ${output_dir}/tb_logs
  name : ${name}
  version : ${run_id}
csv:
  _target_ : pytorch_lightning.loggers.CSVLogger
  save_dir : ${output_dir}/csv_logs
  name : ${name}
  version : ${run_id}
