_target_: prosailvae.datamodules.data_module.ProsailVAEDataModule
config:
  _target_: prosailvae.datamodules.data_module.DataModuleConfig
  patches_dir: "/usr/local/stok/DATA/MMDC/ProsailVAE/PROSAILVAE/s2_patch_dataset/"
  bands: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
