_target_: prosailvae.datamodules.data_module.ProsailVAEDataModule
config:
  _target_: prosailvae.datamodules.data_module.DataModuleConfig
  patches_dir: ${data_dir}/s2_patch_dataset/
  bands: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  batch_size: 4
  max_training_samples: 1000
  max_valid_samples: 10
